name: Jammy CI
on:
  push:
    paths-ignore:
      - 'datasets/**'
      - 'docs/**'
      - 'matlab/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'datasets/**'
      - 'docs/**'
      - 'matlab/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

  # enable manual trigger
  workflow_dispatch:

  # run on first day of the month
  schedule:
    - cron: '0 0 1 * *'

jobs:
  Build:
    name: Build libRSF
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: ./InstallDependencies.bash
        shell: bash

      - name: Configure
        run: cmake --preset ci

      - name: Build
        run: cmake --build --preset ci

      - name: Install
        run: sudo cmake --install build/ci

      - name: Uninstall
        run: sudo cmake --build build/ci --target uninstall

      - name: Tar build directory
        run: tar -czf jammy-build.tar.gz build/ci

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: jammy-build
          path: jammy-build.tar.gz
          if-no-files-found: error

  Test:
    name: Test libRSF
    runs-on: ubuntu-22.04
    needs: [Build]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: jammy-build

      - name: Extract build directory
        run: tar -xzf jammy-build.tar.gz

      - name: Install dependencies
        run: ./InstallDependencies.bash
        shell: bash

      - name: Test
        run: ctest --preset ci
