name: Noble CI
on:
  push:
    paths-ignore:
      - 'datasets/**'
      - 'docs/**'
      - 'matlab/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'datasets/**'
      - 'docs/**'
      - 'matlab/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

  # enable manual trigger
  workflow_dispatch:

  # run on first day of the month
  schedule:
    - cron: '0 0 1 * *'

jobs:
  noble:
    uses: ./.github/workflows/build-and-test.yml
    with:
      os: ubuntu-24.04
